### ISSUE TITLE
Change first day of week

### ISSUE THREAD

**Issue by darxmac** [jivesoftware/PDTSimpleCalendar#27]
Am i blind, or is there no easy way to start the week on mondays ?

**Comment by vdvleon** [comment]
Is this problem solved? Because I seem to have the same problem

**Comment by vdvleon** [comment]
Nevermind, it seems [[NSCalendar currentCalendar] setFirstWeekDay:2]; // monday does not actually change the firstWeekDay propperty of the calendar. The implementation of PDTSimpleCalendar still seems to be correct.

**Comment by jmig** [comment]
For example, If you set the locale to French (or set your phone to French) the calendar will automatically display monday as the first day of the week.

**Comment by vdvleon** [comment]
Yeah indeed, I found out that in the iPhone simulator you can change the locales to Dutch and then the week starts at monday, perfect! I created a week name header above it, taking the firstWeekDay into an account.
