### ISSUE TITLE
Add Events For particular day

### ISSUE THREAD

**Issue by Rix1212** [jivesoftware/PDTSimpleCalendar#46]
![sample](https://cloud.githubusercontent.com/assets/8928756/5226801/fd820e38-7718-11e4-9d70-d3e4d05c8b92.png)
Your are doing a great job thank you for your valuable complement ,I need to know that Is there any provision to add events for dates like the image above
Thanks,
Rix

**Comment by jmig** [comment]
I do not have plans as we mostly use the calendar component as a date selector. However, if you want to build the feature and submit a PR, I'll be happy to look at it.
