### ISSUE TITLE
When using the view controller with a custom timezone the calendar gets messed up

### ISSUE THREAD

**Issue by vdvleon** [jivesoftware/PDTSimpleCalendar#48]
I'm using the PDTSimpleCalendarViewController in the following way (in Swift):

```swift
var vc = PDTSimpleCalendarViewController()
var calendar = NSCalendar(calendarIdentifier: NSGregorianCalendar)!
calendar.locale = NSLocale.currentLocale()
calendar.timeZone = NSDate.localTimeZone()
vc.calendar = calendar
```

NSDate.localTimeZone() is an custom function (an extension). This function gives the original default time zone (from when the app starts up, Europe/Amsterdam in my case), during the rest of the app the default time zone will be UTC.

When using this code the following incorrect calendar is produced: (note, I made this printscreen on the 5th, not the 4th)
![s5egqecwchftlvnpf1voe8ueixg0q6whhdxgmwl_kee](https://cloud.githubusercontent.com/assets/620065/5616276/56f99a32-9503-11e4-861d-c8fa1f364bc5.png)

Is there a way to solve this? (An other solution can be to support to overwrite the 'today' date)

**Comment by jmig** [comment]
I see what's going on. To determine if a cell is today, we compare the date to [NSDate date] which will be using the system default which is GMT.

So we need to take into account the time difference generated by your timezone.

May I ask you why you handle 2 different timezones in your app?

**Comment by vdvleon** [comment]
The strange thing is my time zone difference is only 1 hour, so the [NSDate date] bug is probably not it. But maybe determining the first day of the month etc. is ? 2014-12-31 23:00 vs 2015-01-01 00:00 ?
Anyways, "May I ask you why you handle 2 different timezones in your app?" is a good question I asked myself aswell. I decided that was indeed not the way to go. For this app, a reservation system, we dont store dates with a timezone (so we choose UTC (without daylight saving)). A long story. Instead of chancing the whole app's default timezone to UTC I rewrote the code to only use UTC where necessary. Because I have to send an YYYY-MM-dd HH:mm formatted string to our server, the timezone doesn't matter. So I dont really have to worry about timezones at all because the server will interpreted it as UTC anyways.

**Comment by jmig** [comment]
Glad that you've been able to find an alternative way.
I think you're right, the method to find the first day of the month is probably the one to blame in that case.

Due to the fact that the calendar & the system use 2 different timezones. I created myself a task to investigate that. Thanks!

**Comment by youdy3000** [comment]
Hi Jerome,
Sorry for a basic question. Any chance you have a demo of PDTSimpleCalendar in Swift? 

Bobby

**Comment by ofix-Parul** [comment]
Hello,

Please update if there is a demo code for PDTSimpleCalendar in Swift.

Thanks
