### ISSUE TITLE
setting selectedDate has no effects

### ISSUE THREAD

**Issue by honghaoz** [jivesoftware/PDTSimpleCalendar#55]
This is my code:

```Swift
self.firstDate = NSDate(timeIntervalSinceNow: -60 * 60 * 24 * 365)
self.lastDate = NSDate(timeIntervalSinceNow: 60 * 60 * 24 * 365)
self.selectedDate = NSDate()
```

In the documentation:
/**
 *  Selected date displayed by the calendar.
 *  Changing this value will cause the calendar to scroll to this date (without animation).
 */
You said `Changing this value will cause the calendar to scroll to this date (without animation)`

However, there's no effects. I have to call `self.scrollToSelectedDate(false)`

Maybe it's a bug?

**Comment by archfear** [comment]
I have the same issue.

**Comment by jmig** [comment]
@honghaoz  & @archfear I apologize for this.
That was the previous behavior when `setSelectedDate` was calling `- (void)setSelectedDate:(NSDate *)newSelectedDate animated:(BOOL)animated` under the hood.

As I deprecated `- (void)setSelectedDate:(NSDate *)newSelectedDate animated:(BOOL)animated` I put a warning saying
`__attribute__((deprecated("Use setSelectedDate: instead. Also setSelectedDate doesn't automatically scroll to the selected date. You need to explicitly call scrollToDate:animated: (or scrollToSelectedDate:)")))`

However I forgot to remove the comment on setSelectedDate, so setSelectedDate should not scroll to the date automagically. I'll fix the documentation.
