### ISSUE TITLE
Date Range Issue

### ISSUE THREAD

**Issue by Baldoria** [jivesoftware/PDTSimpleCalendar#63]
Hi, i found out a bug with date ranges.
I first set a range for my calendar and all goes fine.
Than, when I set again the firstDate or lastDate, if the new firstDate falls in the previous month, when I select again a date it crashes with this log message:

*** Assertion failure in -[UICollectionView _endItemAnimations], /SourceCache/UIKit/UIKit-3318.93/UICollectionView.m:3901
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (13) must be equal to the number of sections contained in the collection view before the update (12), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'

Is it me missing something or could you fix this?
I've tried even in your Demo app by setting a new startDate when a date is selected and the same behavior is happening.
Thank you in advance for the help, I'm here for more informations.

**Comment by jmig** [comment]
Sorry for the delay. If you change firstDate or lastDate while the calendar is still on screen, you will need to reload the collection view In order for the proper calculation to happen. `[calendarViewController.collectionView reloadData];` should do the trick.
