### ISSUE TITLE
Not support iOS7

### ISSUE THREAD

**Issue by scorpiozj** [jivesoftware/PDTSimpleCalendar#69]
I want to add the canlendar view as a subview in iOS7:
<pre><code>
PDTSimpleCalendarViewController *vc = [[PDTSimpleCalendarViewController alloc] init];
    vc.firstDate = [NSDate date];
    NSDateComponents *offsetComponents = [[NSDateComponents alloc] init];
    offsetComponents.month = 3;
    NSDate *lastDate =[vc.calendar dateByAddingComponents:offsetComponents toDate:[NSDate date] options:0];
    vc.lastDate = lastDate;
[self addChildViewController:vc];
    [self.view addSubview:vc.view];
    [vc didMoveToParentViewController:self];

</code></pre>
It has long time no responding.
I also try to present, like:
<pre><code>
    [self presentViewController:vc animated:YES completion:^{
        
    }];
</code></pre>
It also has long time no responding.   
How can use it in iOS7 correctly?

Testing with Xcode6.4 Simulater5s 7.1

**Comment by vbonluk** [comment]
I have this problem too , hope fix it. I can not find where it goning wrong.

**Comment by Synendo** [comment]
When I open PDTSimpleCalendarViewController from a UIPopoverController it loops in PDTSimpleCalendarViewController's collectionView:layout:sizeForItemAtIndexPath: in iOS 7. No issues in iOS 8.

**Comment by scorpiozj** [comment]
see this temporary fixing:
[Pull Request](https://github.com/jivesoftware/PDTSimpleCalendar/pull/70)

**Comment by jmig** [comment]
Ok so rangeOfUnit on iOS7 when calculating the number of element per section is returning 2147483647 (so the CollectionView tries to allocate TONS of cell).

I'm trying to find a proper fix that would work both on iOS7 & iOS8

**Comment by jmig** [comment]
Thanks @scorpiozj  for tracking it down. I just merged the fix to master & cut a new release. Please update to 0.9.1.
