### ISSUE TITLE
weekdayHeaderEnabled = true - does not show any Day heading

### ISSUE THREAD

**Issue by rustymagnet3000** [jivesoftware/PDTSimpleCalendar#86]
Any idea if I have made a mistake or stumbled on a bug?  I have been using PDTSimpleCalender in my app for about 4 months.  Works great.  Love this library.

Issue: When I set the weekdayHeaderEnabled to true, nothing happens.  I can see the option (the predictive text picks the fact it can see the weekdayHeaderEnabled option) I can even set the values.  Everything compiles fine.

I am using the latest version of PDTSimpleCalender (v0.9.1)

internal class calenderCollectionView: PDTSimpleCalendarViewController, PDTSimpleCalendarViewDelegate {

```
var onDataAvailable : ((data: NSDate) -> ())?

func sendData(data: NSDate) {
    // Whenever you want to send data back to viewController1, check
    // if the closure is implemented and then call if it is
    self.onDataAvailable?(data: data)
}

override func viewDidLoad() {
    super.viewDidLoad()
    title = "Select Date"

    // initialize my calender
    self.delegate = self
    self.firstDate = NSDate().month - 1
    self.lastDate = NSDate().day + 1
    self.weekdayHeaderEnabled = true
    self.weekdayTextType = .Short
    self.calendar = NSCalendar.currentCalendar()
}

func simpleCalendarViewController(controller: PDTSimpleCalendarViewController!, isEnabledDate date: NSDate!) -> Bool {
    return true
}

func simpleCalendarViewController(controller: PDTSimpleCalendarViewController!, didSelectDate date: NSDate!) {
    sendData(date)
    dismissViewControllerAnimated(true, completion: nil)
}

func simpleCalendarViewController(controller: PDTSimpleCalendarViewController!, shouldUseCustomColorsForDate date: NSDate!) -> Bool {
    return true
}

func simpleCalendarViewController(controller: PDTSimpleCalendarViewController!, circleColorForDate date: NSDate!) -> UIColor! {
    return DashboardKit.niceBlueColor
}

func simpleCalendarViewController(controller: PDTSimpleCalendarViewController!, textColorForDate date: NSDate!) -> UIColor! {
    return UIColor.whiteColor()
}
```

}

**Comment by csrking** [comment]
Try setting your view-controller’s ‘edgesForExtendedLayout’ to UIEdgeRectNone.

I recall experiencing the same thing that you are describing – assuming that I am understanding you correctly – and I found code similar to the above in the sample which solved the problem.

-- /chris

**Comment by rustymagnet3000** [comment]
Great idea, @csrking 

Sadly, it did not work. See how I added your suggestion into my setup of my PDT calender..

```
    self.delegate = self
    self.firstDate = NSDate().month - 1
    self.lastDate = NSDate().day + 1
    self.edgesForExtendedLayout = .None
    self.weekdayHeaderEnabled = true
    self.weekdayTextType = .Short
    self.calendar = NSCalendar.currentCalendar()
```

**Comment by dzorrilla** [comment]
@youdy3000 try setting the values before you present the view controller. 

vc.weekdayHeaderEnabled = true
vc.weekdayTextType = .Short
vc.edgesForExtendedLayout = .None
let nav = UINavigationController.init(rootViewController: vc)
navigationController?.presentViewController(nav, animated: true, completion: { () -> Void in })

**Comment by rustymagnet3000** [comment]
@dzorrilla thanks for answering.  I like your approach.  On first attempt it didn't work but I think was more related to my code. I used the storyboard to connect everything & manage VC connections and navigiation controllers.  But I will write it in code (and avoid storyboard).

Before I do, have you got a swift example where you used PDTSimpleCalender?

**Comment by rustymagnet3000** [comment]
@dzorrilla & @csrking  thank you both.  Your answers were the clues I needed. I went back to the objective-C example from @jmig.  The key line to achieve what I wanted - while maintaining a good looking Navigation Controller - was calendarViewController.edgesForExtendedLayout = .None

import UIKit
import PDTSimpleCalendar

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

```
var window : UIWindow?
var appNavigationController : UINavigationController?

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    window = UIWindow(frame: UIScreen.mainScreen().bounds)

    let calendarViewController: PDTSimpleCalendarViewController = PDTSimpleCalendarViewController()
    calendarViewController.calendar = NSCalendar.currentCalendar()
    calendarViewController.lastDate = NSDate()
    calendarViewController.weekdayHeaderEnabled = true
    calendarViewController.weekdayTextType = .Short
    **calendarViewController.edgesForExtendedLayout = .None**

    appNavigationController = UINavigationController()
    self.appNavigationController!.pushViewController(calendarViewController, animated: false)


    window!.rootViewController = appNavigationController
    window!.makeKeyAndVisible()

    return true
```

**Comment by jmig** [comment]
Glad you were able to find a solution!
