### ISSUE TITLE
Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:]

### ISSUE THREAD

**Issue by Dalein** [jivesoftware/PDTSimpleCalendar#88]
I want to show calendar as a view in my viewController. I create caledarVC standart way:

```
 PDTSimpleCalendarViewController *calendarViewController = [[PDTSimpleCalendarViewController alloc] init];
    [calendarViewController setDelegate:self];
    calendarViewController.weekdayHeaderEnabled = YES;
    calendarViewController.weekdayTextType = PDTSimpleCalendarViewWeekdayTextTypeVeryShort;
```

But I show calendar VC like this: 
 `[calendarViewController showInView:self.view animated:YES];`

 I added in PDTSimpleCalendarViewController.m this method:

```
- (void)showInView:(UIView *)aView animated:(BOOL)animated
{
    CGRect calendarFrame = self.view.frame;
    calendarFrame.origin.y = 64;
    calendarFrame.size.height = CGRectGetHeight(calendarFrame)/1.5;
    self.view.frame = calendarFrame;

    dispatch_async(dispatch_get_main_queue(), ^{
        [aView addSubview:self.view];
    });
}

```

In time when calendar appeared, error occurred:**Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:]**
How can I show calendar view like I want?

**Comment by jmig** [comment]
If you want to display the calendar inside another VC view you should implement UIViewController containment.
https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html

**Comment by Dalein** [comment]
Thanks! I had to understand it by myself
