### ISSUE TITLE
viewForSupplementaryElementOfKind analysis issue

### ISSUE THREAD

**Issue by csrking** [jivesoftware/PDTSimpleCalendar#94]
The implementation of this method in the PDTSimpleCalendarViewController.m file is returning nil in the case where the 'kind' parameter is anything except for UICollectionElementKindSectionHeader.

Xcode 8 presents an analysis issue for this -- Null is returned from a method that is expected to return a non-null value -- and the documentation for this method states that it must not return nil.

**Comment by adonoho** [comment]
Because the calendar does not use footers, the problem you identify does not occur in practice.

If you are still worried about this code path, here is untested code to place in lieu of the `return nil;`:

```
else {

    PDTSimpleCalendarViewHeader *headerView = [self.collectionView dequeueReusableSupplementaryViewOfKind:UICollectionElementKindSectionHeader withReuseIdentifier:PDTSimpleCalendarViewHeaderIdentifier forIndexPath:indexPath];

    headerView.bounds = CGRectZero;

    return headerView;
}
```

**Comment by csrking** [comment]
Good enough I suppose; thanks.  I was doing something similar to return a zero-rect dummy view in this case to eliminate the analysis warning.
